onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider iTLB
add wave -noupdate /mips_testbench/mips/iTLB/clk
add wave -noupdate /mips_testbench/mips/iTLB/reset
add wave -noupdate /mips_testbench/mips/iTLB/mode
add wave -noupdate /mips_testbench/mips/iTLB/write
add wave -noupdate /mips_testbench/mips/iTLB/vaddr
add wave -noupdate /mips_testbench/mips/iTLB/paddr_new
add wave -noupdate /mips_testbench/mips/iTLB/paddr
add wave -noupdate /mips_testbench/mips/iTLB/hit
add wave -noupdate -divider iCache
add wave -noupdate /mips_testbench/mips/iCache/clk
add wave -noupdate /mips_testbench/mips/iCache/reset
add wave -noupdate /mips_testbench/mips/iCache/addr_tag
add wave -noupdate /mips_testbench/mips/iCache/addr_data
add wave -noupdate /mips_testbench/mips/iCache/write_data
add wave -noupdate /mips_testbench/mips/iCache/write_tag
add wave -noupdate /mips_testbench/mips/iCache/op_type_data
add wave -noupdate /mips_testbench/mips/iCache/din_data
add wave -noupdate /mips_testbench/mips/iCache/din_tag
add wave -noupdate /mips_testbench/mips/iCache/dout_data
add wave -noupdate /mips_testbench/mips/iCache/dout_tag
add wave -noupdate /mips_testbench/mips/iCache/dout_addr_tag
add wave -noupdate /mips_testbench/mips/iCache/hit
add wave -noupdate /mips_testbench/mips/iCache/dirty
add wave -noupdate /mips_testbench/mips/iCache/cache_valid
add wave -noupdate /mips_testbench/mips/iCache/cache_dirty
add wave -noupdate /mips_testbench/mips/iCache/cache_tags
add wave -noupdate /mips_testbench/mips/iCache/cache_data
add wave -noupdate -divider IF-ID
add wave -noupdate /mips_testbench/mips/bank_IF_ID/clk
add wave -noupdate /mips_testbench/mips/bank_IF_ID/reset
add wave -noupdate /mips_testbench/mips/bank_IF_ID/load
add wave -noupdate /mips_testbench/mips/bank_IF_ID/instruction_IF
add wave -noupdate /mips_testbench/mips/bank_IF_ID/PC_IF
add wave -noupdate /mips_testbench/mips/bank_IF_ID/iTLB_hit_IF
add wave -noupdate /mips_testbench/mips/bank_IF_ID/instruction_ID
add wave -noupdate /mips_testbench/mips/bank_IF_ID/PC_ID
add wave -noupdate /mips_testbench/mips/bank_IF_ID/iTLB_hit_ID
add wave -noupdate -divider register-bank
add wave -noupdate /mips_testbench/mips/register_bank/clk
add wave -noupdate /mips_testbench/mips/register_bank/reset
add wave -noupdate /mips_testbench/mips/register_bank/rs
add wave -noupdate /mips_testbench/mips/register_bank/rt
add wave -noupdate /mips_testbench/mips/register_bank/rw
add wave -noupdate /mips_testbench/mips/register_bank/bus_rw
add wave -noupdate /mips_testbench/mips/register_bank/reg_write
add wave -noupdate /mips_testbench/mips/register_bank/bus_rs
add wave -noupdate /mips_testbench/mips/register_bank/bus_rt
add wave -noupdate /mips_testbench/mips/register_bank/reg_file
add wave -noupdate -divider ID-EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/clk
add wave -noupdate /mips_testbench/mips/bank_ID_EX/reset
add wave -noupdate /mips_testbench/mips/bank_ID_EX/load
add wave -noupdate /mips_testbench/mips/bank_ID_EX/instruction_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/mode_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/bus_rs_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/bus_rt_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/PC_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/iTLB_hit_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/inm_ext_ID
add wave -noupdate /mips_testbench/mips/bank_ID_EX/instruction_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/mode_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/bus_rs_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/bus_rt_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/PC_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/iTLB_hit_EX
add wave -noupdate /mips_testbench/mips/bank_ID_EX/inm_ext_EX
add wave -noupdate -divider EX-LU
add wave -noupdate /mips_testbench/mips/bank_EX_LU/clk
add wave -noupdate /mips_testbench/mips/bank_EX_LU/reset
add wave -noupdate /mips_testbench/mips/bank_EX_LU/load
add wave -noupdate /mips_testbench/mips/bank_EX_LU/instruction_EX
add wave -noupdate /mips_testbench/mips/bank_EX_LU/mode_EX
add wave -noupdate /mips_testbench/mips/bank_EX_LU/ALU_out_EX
add wave -noupdate /mips_testbench/mips/bank_EX_LU/tag_EX
add wave -noupdate /mips_testbench/mips/bank_EX_LU/rs_bus_EX
add wave -noupdate /mips_testbench/mips/bank_EX_LU/instruction_LU
add wave -noupdate /mips_testbench/mips/bank_EX_LU/mode_LU
add wave -noupdate /mips_testbench/mips/bank_EX_LU/ALU_out_LU
add wave -noupdate /mips_testbench/mips/bank_EX_LU/tag_LU
add wave -noupdate /mips_testbench/mips/bank_EX_LU/rs_bus_LU
add wave -noupdate -divider dTLB
add wave -noupdate /mips_testbench/mips/dTLB/clk
add wave -noupdate /mips_testbench/mips/dTLB/reset
add wave -noupdate /mips_testbench/mips/dTLB/mode
add wave -noupdate /mips_testbench/mips/dTLB/write
add wave -noupdate /mips_testbench/mips/dTLB/vaddr
add wave -noupdate /mips_testbench/mips/dTLB/paddr_new
add wave -noupdate /mips_testbench/mips/dTLB/paddr
add wave -noupdate /mips_testbench/mips/dTLB/hit
add wave -noupdate -divider dCache
add wave -noupdate /mips_testbench/mips/dCache/clk
add wave -noupdate /mips_testbench/mips/dCache/reset
add wave -noupdate /mips_testbench/mips/dCache/addr_tag
add wave -noupdate /mips_testbench/mips/dCache/addr_data
add wave -noupdate /mips_testbench/mips/dCache/write_data
add wave -noupdate /mips_testbench/mips/dCache/write_tag
add wave -noupdate /mips_testbench/mips/dCache/op_type_data
add wave -noupdate /mips_testbench/mips/dCache/din_data
add wave -noupdate /mips_testbench/mips/dCache/din_tag
add wave -noupdate /mips_testbench/mips/dCache/dout_data
add wave -noupdate /mips_testbench/mips/dCache/dout_tag
add wave -noupdate /mips_testbench/mips/dCache/dout_addr_tag
add wave -noupdate /mips_testbench/mips/dCache/hit
add wave -noupdate /mips_testbench/mips/dCache/dirty
add wave -noupdate /mips_testbench/mips/dCache/cache_tags
add wave -noupdate /mips_testbench/mips/dCache/cache_data
add wave -noupdate -divider LU-MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/clk
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/reset
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/load
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/instruction_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/paddr_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/ALU_out_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/rs_bus_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/tag_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/hit_dTLB_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/hit_dCache_LU
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/instruction_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/paddr_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/ALU_out_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/rs_bus_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/tag_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/hit_dTLB_MEM
add wave -noupdate /mips_testbench/mips/bank_LU_MEM/hit_dCache_MEM
add wave -noupdate -divider MEM-MUL4
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/clk
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/reset
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/load
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/instruction_MEM
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/ALU_out_MEM
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/tag_MEM
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/instruction_MUL4
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/ALU_out_MUL4
add wave -noupdate /mips_testbench/mips/bank_MEM_MUL4/tag_MUL4
add wave -noupdate -divider MUL4-MUL5
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/clk
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/reset
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/load
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/instruction_MUL4
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/ALU_out_MUL4
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/tag_MUL4
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/instruction_MUL5
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/ALU_out_MUL5
add wave -noupdate /mips_testbench/mips/bank_MUL4_MUL5/tag_MUL5
add wave -noupdate -divider ROB
add wave -noupdate /mips_testbench/mips/ROB/clk
add wave -noupdate /mips_testbench/mips/ROB/reset
add wave -noupdate /mips_testbench/mips/ROB/write_EX
add wave -noupdate /mips_testbench/mips/ROB/tag_EX
add wave -noupdate /mips_testbench/mips/ROB/state_EX
add wave -noupdate /mips_testbench/mips/ROB/addr_EX
add wave -noupdate /mips_testbench/mips/ROB/value_EX
add wave -noupdate /mips_testbench/mips/ROB/PC_EX
add wave -noupdate /mips_testbench/mips/ROB/instr_EX
add wave -noupdate /mips_testbench/mips/ROB/mode_EX
add wave -noupdate /mips_testbench/mips/ROB/write_MEM
add wave -noupdate /mips_testbench/mips/ROB/tag_MEM
add wave -noupdate /mips_testbench/mips/ROB/state_MEM
add wave -noupdate /mips_testbench/mips/ROB/addr_MEM
add wave -noupdate /mips_testbench/mips/ROB/value_MEM
add wave -noupdate /mips_testbench/mips/ROB/PC_MEM
add wave -noupdate /mips_testbench/mips/ROB/instr_MEM
add wave -noupdate /mips_testbench/mips/ROB/mode_MEM
add wave -noupdate /mips_testbench/mips/ROB/write_MUL5
add wave -noupdate /mips_testbench/mips/ROB/tag_MUL5
add wave -noupdate /mips_testbench/mips/ROB/state_MUL5
add wave -noupdate /mips_testbench/mips/ROB/addr_MUL5
add wave -noupdate /mips_testbench/mips/ROB/value_MUL5
add wave -noupdate /mips_testbench/mips/ROB/PC_MUL5
add wave -noupdate /mips_testbench/mips/ROB/instr_MUL5
add wave -noupdate /mips_testbench/mips/ROB/mode_MUL5
add wave -noupdate /mips_testbench/mips/ROB/write_head
add wave -noupdate /mips_testbench/mips/ROB/state_head_write
add wave -noupdate /mips_testbench/mips/ROB/addr_head_write
add wave -noupdate /mips_testbench/mips/ROB/value_head_write
add wave -noupdate /mips_testbench/mips/ROB/PC_head_write
add wave -noupdate /mips_testbench/mips/ROB/instr_head_write
add wave -noupdate /mips_testbench/mips/ROB/mode_head_write
add wave -noupdate /mips_testbench/mips/ROB/head
add wave -noupdate /mips_testbench/mips/ROB/tail
add wave -noupdate /mips_testbench/mips/ROB/instruction_ID
add wave -noupdate /mips_testbench/mips/ROB/rs_state
add wave -noupdate /mips_testbench/mips/ROB/rt_state
add wave -noupdate /mips_testbench/mips/ROB/rs_value
add wave -noupdate /mips_testbench/mips/ROB/rt_value
add wave -noupdate /mips_testbench/mips/ROB/state_head
add wave -noupdate /mips_testbench/mips/ROB/addr_head
add wave -noupdate /mips_testbench/mips/ROB/value_head
add wave -noupdate /mips_testbench/mips/ROB/PC_head
add wave -noupdate /mips_testbench/mips/ROB/instr_head
add wave -noupdate /mips_testbench/mips/ROB/mode_head
add wave -noupdate /mips_testbench/mips/ROB/empty_entries
add wave -noupdate /mips_testbench/mips/ROB/ROB_states
add wave -noupdate /mips_testbench/mips/ROB/ROB_addrs
add wave -noupdate /mips_testbench/mips/ROB/ROB_values
add wave -noupdate /mips_testbench/mips/ROB/ROB_pcs
add wave -noupdate /mips_testbench/mips/ROB/ROB_instrs
add wave -noupdate /mips_testbench/mips/ROB/ROB_modes
add wave -noupdate /mips_testbench/mips/ROB/used_entries
add wave -noupdate -divider RAM
add wave -noupdate /mips_testbench/mips/RAM/clk
add wave -noupdate /mips_testbench/mips/RAM/addr_rw
add wave -noupdate /mips_testbench/mips/RAM/addr_r
add wave -noupdate /mips_testbench/mips/RAM/din
add wave -noupdate /mips_testbench/mips/RAM/read_rw
add wave -noupdate /mips_testbench/mips/RAM/read_r
add wave -noupdate /mips_testbench/mips/RAM/write_rw
add wave -noupdate /mips_testbench/mips/RAM/port_rw_state
add wave -noupdate /mips_testbench/mips/RAM/port_r_state
add wave -noupdate /mips_testbench/mips/RAM/dout_rw
add wave -noupdate /mips_testbench/mips/RAM/dout_r
add wave -noupdate /mips_testbench/mips/RAM/DATA
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 347
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1240 ps}
